- init:
    assign:
      - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - location: "us-central1"
      - zone: "us-central1-f"
      - bucket_name: ${ project_id }
      - job_name: "import-openfoodfacts-products-to-bigquery"
      - input: "https://static.openfoodfacts.org/data/openfoodfacts-products.jsonl.gz"
      - table: "openfoodfacts-json"
      - dataset: "raw"
      - temp_location: ${"gs://" + bucket_name + "/dataflow/temp"}
      - template_path: ${"gs://" + bucket_name + "/dataflow/import-openfoodfacts-products-to-bigquery"}
- create_job:
    call: googleapis.dataflow.v1b3.projects.jobs.create
    args:
      projectId: ${project_id}
      body:
        jobName: ${job_name}
        environment:
          tempLocation: ${temp_location}
        gcsPath: ${template_path}
- the_end:
    return: "SUCCESS"