config {
  type: "table",
  bigquery:{
    clusterBy: ["lang"]
  }
}

SELECT
    JSON_EXTRACT_SCALAR(raw, "$.id") id,
    JSON_EXTRACT_SCALAR(raw, "$.code") code,
    CAST(JSON_QUERY(raw, "$.created_t") AS INT64) created_t,
    TIMESTAMP_SECONDS(CAST(JSON_QUERY(raw, "$.created_t") AS INT64)) created_timestamp,
    JSON_EXTRACT_SCALAR(raw, "$.creator") creator,
    JSON_EXTRACT_SCALAR(raw, "$.last_modified_by") last_modified_by,
    CAST(JSON_QUERY(raw, "$.last_modified_t") AS INT64) last_modified_t,
    TIMESTAMP_SECONDS(CAST(JSON_QUERY(raw, "$.last_modified_t") AS INT64)) last_modified_timestamp,
    JSON_EXTRACT_SCALAR(raw, "$.product_name") product_name,
    JSON_EXTRACT_SCALAR(raw, "$.quantity") quantity,
    JSON_EXTRACT_SCALAR(raw, "$.nutrition_data_per") nutrition_data_per,
    JSON_EXTRACT_SCALAR(raw, "$.brands") brands,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.brands_tags") brands_tags,
    JSON_EXTRACT_SCALAR(raw, "$.lang") lang,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.categories_properties_tags") categories_properties_tags,
    SPLIT(JSON_EXTRACT_SCALAR(raw, "$.data_sources"), ",") data_sources,
    SPLIT(JSON_EXTRACT_SCALAR(raw, "$.categories"), ",") categories,
    JSON_EXTRACT_SCALAR(raw, "$.ingredients_text") ingredients_text,
    JSON_EXTRACT_SCALAR(raw, "$.nutriments") nutriments,
    JSON_EXTRACT_SCALAR(raw, "$.ecoscore_grade") ecoscore_grade,
    JSON_EXTRACT_SCALAR(raw, "$.images") images,
    JSON_EXTRACT_SCALAR(raw, "$.labels") labels,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.labels_tags") labels_tags,
    JSON_EXTRACT_SCALAR(raw, "$.labels_lc") labels_lc,
    JSON_EXTRACT_SCALAR(raw, "$.countries") countries,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.countries_tags") countries_tags,
    JSON_EXTRACT_SCALAR(raw, "$.countries_lc") countries_lc,
    JSON_EXTRACT_SCALAR(raw, "$.traces") traces,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.traces_tags") traces_tags,
    JSON_EXTRACT_SCALAR(raw, "$.serving_size") serving_size,
    JSON_EXTRACT_SCALAR(raw, "$.additives_n") additives_n,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.additives_tags") additives_tags,
    JSON_EXTRACT_SCALAR(raw, "$.ingredients_from_palm_oil_n") ingredients_from_palm_oil_n,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.ingredients_from_palm_oil_tags") ingredients_from_palm_oil_tags,
    JSON_EXTRACT_SCALAR(raw, "$.ingredients_that_may_be_from_palm_oil_n") ingredients_that_may_be_from_palm_oil_n,
    JSON_EXTRACT_STRING_ARRAY(raw, "$.ingredients_that_may_be_from_palm_oil_tags") ingredients_that_may_be_from_palm_oil_tags,



-- general information --
--     prefix
--     url
--     generic_name
--     quantity

-- tags --
-- packaging
-- packaging_tags
-- categories
-- categories_tags
-- categories_fr
-- origins
-- origins_tags
-- manufacturing_places
-- manufacturing_places_tags
-- labels_fr
-- emb_codes
-- emb_codes_tags
-- first_packaging_code_geo
-- cities
-- cities_tags
-- purchase_places
-- stores
-- countries_fr

-- ingredients --


-- misc. data --

--     no_nutriments
--     additives
--     ingredients_from_palm_oil
--     ingredients_that_may_be_from_palm_oil
--     nutrition_grade_fr
--     main_category
--     main_category_fr
--     image_url
--     image_small_url

-- # nutrition facts: --

-- energy_100g
-- energy-kj_100g
-- energy-kcal_100g
-- proteins_100g
-- casein_100g
-- serum-proteins_100g
-- nucleotides_100g
-- carbohydrates_100g
-- sugars_100g
-- sucrose_100g
-- glucose_100g
-- fructose_100g
-- lactose_100g
-- maltose_100g
-- maltodextrins_100g
-- starch_100g
-- polyols_100g
-- fat_100g
-- saturated-fat_100g
-- butyric-acid_100g
-- caproic-acid_100g
-- caprylic-acid_100g
-- capric-acid_100g
-- lauric-acid_100g
-- myristic-acid_100g
-- palmitic-acid_100g
-- stearic-acid_100g
-- arachidic-acid_100g
-- behenic-acid_100g
-- lignoceric-acid_100g
-- cerotic-acid_100g
-- montanic-acid_100g
-- melissic-acid_100g
-- monounsaturated-fat_100g
-- polyunsaturated-fat_100g
-- omega-3-fat_100g
-- alpha-linolenic-acid_100g
-- eicosapentaenoic-acid_100g
-- docosahexaenoic-acid_100g
-- omega-6-fat_100g
-- linoleic-acid_100g
-- arachidonic-acid_100g
-- gamma-linolenic-acid_100g
-- dihomo-gamma-linolenic-acid_100g
-- omega-9-fat_100g
-- oleic-acid_100g
-- elaidic-acid_100g
-- gondoic-acid_100g
-- mead-acid_100g
-- erucic-acid_100g
-- nervonic-acid_100g
-- trans-fat_100g
-- cholesterol_100g
-- fiber_100g
-- sodium_100g
-- alcohol_100g
-- vitamin-a_100g
-- vitamin-d_100g
-- vitamin-e_100g
-- vitamin-k_100g
-- vitamin-c_100g
-- vitamin-b1_100g
-- vitamin-b2_100g
-- vitamin-pp_100g
-- vitamin-b6_100g
-- vitamin-b9_100g
-- vitamin-b12_100g
-- biotin_100g
-- pantothenic-acid_100g
-- silica_100g
-- bicarbonate_100g
-- potassium_100g
-- chloride_100g
-- calcium_100g
-- phosphorus_100g
-- iron_100g
-- magnesium_100g
-- zinc_100g
-- copper_100g
-- manganese_100g
-- fluoride_100g
-- selenium_100g
-- chromium_100g
-- molybdenum_100g
-- iodine_100g
-- caffeine_100g
-- taurine_100g
-- ph_100g
-- fruits-vegetables-nuts_100g
-- carbon-footprint_100g
-- nutrition-score-fr_100g
-- nutrition-score-uk_100g

FROM
    `openfoodfacts-datasets.raw.openfoodfacts_json`
