name: Terraform IaC

on:
  pull_request:
    types:
      - closed
    paths:
      - terraform/**

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    name: 'IaC'
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.5
      - name: Terraform Init
        id: init
        run: |
          cd ./terraform/iac
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd ./terraform/iac
          terraform validate

      - name: Terraform Apply
        id: plan
        run: |
          cd ./terraform/iac
          terraform apply -auto-approve
